# Generated by Django 3.1.4 on 2021-01-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210107_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_transactions', to='main.block'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='maturity_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matured_transactions', to='main.block'),
        ),
    ]
