# Generated by Django 3.1.4 on 2021-01-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210108_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='transaction_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_transactions', to='main.block'),
        ),
    ]
