# Generated by Django 3.1.4 on 2021-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_funding_transaction_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='bch_usd_price',
            field=models.FloatField(default=0),
        ),
    ]
