# Generated by Django 3.1.4 on 2021-01-15 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_block_bch_usd_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contract_satoshis', models.FloatField()),
                ('hedge_usd_payout', models.FloatField()),
                ('long_usd_payout', models.FloatField()),
                ('approx_hedge_payin_satoshis', models.FloatField()),
                ('approx_long_payin_satoshis', models.FloatField()),
                ('approx_long_usd_payin', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterField(
            model_name='funding',
            name='hedge_units_x_sats_per_bch_high_trunc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='high_liquidation_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='low_liquidation_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='payout_sats_low_trunc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='hedge_satoshis',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='long_satoshis',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='oracle_price',
            field=models.FloatField(),
        ),
    ]
