# Generated by Django 3.1.4 on 2021-01-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210115_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ('-transaction_block__timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'ordering': ('-block__timestamp',)},
        ),
    ]
