# Generated by Django 3.1.4 on 2021-01-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210115_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='approx_hedge_gain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='approx_hedge_usd_payin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='approx_long_gain',
            field=models.FloatField(default=0),
        ),
    ]
