# Generated by Django 3.1.4 on 2021-01-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210118_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='approx_hedge_gain',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='approx_hedge_payin_satoshis',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='approx_hedge_usd_payin',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='approx_long_gain',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='approx_long_payin_satoshis',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='approx_long_usd_payin',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='hedge_usd_payout',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='long_usd_payout',
        ),
        migrations.AddField(
            model_name='metric',
            name='usd_payouts',
            field=models.JSONField(default=dict),
        ),
    ]
